### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by VanessaAoki** [LoxiasCam/private-events#2]
Hey Mar, great project so far! This is a big project, so don't worry about it.

I do have some suggestions:
- For the event model, you don't have to set the foreign_key, having the class_name is enough;
- For the user model, you should have something like this: 
`has_many :created_events, foreign_key: :creator_id, class_name: 'Event', dependent: :destroy`
> 1. You need to set the foreign_key here because you don't have a table called "creator";
> 2. The class_name should be 'Event' because that's the table you are "looking for";
> 3. Dependent destroy to guarantee you won't have a bunch of events without a creator in case the user gets deleted;

Keep up the great work!

**Comment by vichuge** [comment]
What Vanessa said 🏭

**Comment by marilirulita** [comment]
done!!
