### ISSUE TITLE
Peer-to-peer code

### ISSUE THREAD

**Issue by VanessaAoki** [LoxiasCam/private-events#4]
Mar, this project looks amazing! Congratulations!

I do have a suggestion for you: you should have an unattended button.

To do that you could do something like this:
In your vote model : `validates :user_id, uniqueness: { scope: :article_id }`
> This is so that a user can only attend one time.

To make an unnattend button:
```
def attend_button(ev)
  if current_user
    attend = Attend.find_by(event: ev, user: current_user)
      if vote
        button_to('Click to Unvote!', event_attend_path(id: attend.id, event_id: ev.id), method: :delete)
      else
        button_to('Click to Attend!', event_attends_path(event_id: ev.id), method: :post)
      end
  else
    link_to('LOG IN to vote!', user_session_path)
  end
end
```
> Note that some of the routes might be different for you.

Hope this helps you!
Keep up the great work!

**Comment by marilirulita** [comment]
Done! thanks for suggestion :D
